apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  homelab.server: |
    homelab.azuanz.com:53 {
        errors
        cache 30
        forward . 192.168.68.151
    }