---
# Secret created separately with kubectl
# kubectl create secret generic radarr-api-key -n media --from-literal=api-key='YOUR_API_KEY'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exportarr-radarr
  namespace: media
  labels:
    app: exportarr-radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exportarr-radarr
  template:
    metadata:
      labels:
        app: exportarr-radarr
    spec:
      containers:
        - name: exportarr
          image: ghcr.io/onedr0p/exportarr:v2.0.1
          args:
            - radarr
            - --port
            - "9708"
            - --url
            - "http://radarr.media:7878"
            - --api-key-file
            - "/secrets/api-key"
          ports:
            - containerPort: 9708
              name: metrics
          volumeMounts:
            - name: api-key
              mountPath: /secrets
              readOnly: true
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 100m
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: api-key
          secret:
            secretName: radarr-api-key
---
apiVersion: v1
kind: Service
metadata:
  name: exportarr-radarr
  namespace: media
  labels:
    app: exportarr-radarr
spec:
  selector:
    app: exportarr-radarr
  ports:
    - name: metrics
      port: 9708
      targetPort: 9708
