namespace: nginx

image:
  repository: nginx
  tag: "1.29.1"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: LoadBalancer
  port: 80
  loadBalancerIP: 192.168.68.151
  annotations:
    metallb.universe.tf/address-pool: lan-pool

resources:
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"

indexHtml: |
  <!doctype html>
  <html>
    <head><meta charset="utf-8"><title>nginx on k3s</title></head>
    <body style="font-family: system-ui; margin: 2rem">
      <h1>It works 🎉</h1>
      <p>This is nginx running on k3s (no Traefik yet).</p>
    </body>
  </html>
