apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: loki
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`loki.homelab.azuanz.com`)
      kind: Rule
      services:
        - name: loki-gateway
          port: 80
  tls:
    secretName: homelab-certificate-secret
