deploymentMode: SingleBinary

loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  storage:
    type: filesystem

  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  limits_config:
    retention_period: 720h # 30 days

singleBinary:
  replicas: 1

  persistence:
    enabled: true
    size: 50Gi
    storageClass: local-path

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

gateway:
  enabled: true
  replicas: 1

  service:
    type: ClusterIP
    port: 80

monitoring:
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack

  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false

test:
  enabled: false

chunksCache:
  enabled: false

resultsCache:
  enabled: false
