---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCETKt7NGn2p+3lGkPYq4BLF37aY85SA9fADsFK5D4YSiKnAONUO2tErYzQNImzqjEbmEYrABo18MJdMH6iKWj7PExBZi5+1W0G9JzTQu7P8+JgUI++HBckbIU3siGvMT98ZiQGVhbR2c7hJPsmdJoXD8sUpCyJfGOBz4uQ5hGImYLsnr/rHeMml3ysGGx3HkdTxgLddVKZlLKK9b3RMll+Ateu5vYr+g0Jg6L9egy431fKp9wRRedLQNLg2izIsqG4kOCPuNLZBZM/OjOHRpX89QFRDSbn27g1+6TlsfCKnsNhvUItSF6NbzzP+4bgZprcmmyRLD08PfyiI0B4znQI529bBakVJm+q/c/aYWuukklhbVSN7Ql9y89Z+iGgSK+VXOjn9HotN9QfYJa/uQfOOIvhTbIDB562XPh3Zkv0uRuZjv9jh5HUcUQhZDRvlnptW6X7hVD2ZhmJt0g3A/KOLZuuclz8B1cNiVT7T2NPjdk422Jbd+kZ7Hjo5OKEGhKRrJaQy9p2Awbz725TX4lbhTxrHaHUt5H8meL+gAXNgGYxJR13JlUN7aGBHMwdVMCnNCeyiu2VcmyiL0fNcvS3kh+3yUn4Svy4GD+vadhuYuK8ZtrJIrbrPysntKeeWc1t67lx6F5fEMkjW8gab5gjYyYw3HF2JldY1WyxfwjIjzTdfVH2Mg7edx0uNPBmcICZbSvyckoNtVe+1e9SQ6busNNgcsXctvFaC/qGWAmTw+U9ayl0MvfF
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
