apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
{{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
