apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-synology-speedtest
spec:
  capacity:
    storage: 5Gi
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.68.60
    path: /volume1/family/apps/speedtest/config
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-config
  namespace: speedtest-tracker
spec:
  storageClassName: ""
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-synology-speedtest
