apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-synology-media
spec:
  capacity:
    storage: 100Ti
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.68.60
    path: /volume1/family/media
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-synology-media-rwx
  namespace: media
spec:
  storageClassName: ""
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 100Ti
  volumeName: pv-synology-media
